language: python

python: 
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - coverage run --source test -m pytest -v 

after_success:
  - coveralls